### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by Apb58**
Adding Markdown and Knit files describing code and algorithm. 
Added Example SAM files and small markdown changes
Added UMI changes

### CODE REVIEW

**Comment by Leslie-C** [comment]
I think samtools sort is capable of handling SAM files without converting to BAM first. I know it will write out a SAM file with the ```-o``` option

**Comment by Leslie-C** [comment]
What is the purpose of creating a "standard" position relative to the first read of the "chunk"?

**Comment by Leslie-C** [comment]
I think as presented your chunking strategy will slow you down. Also, what happens when you hit a new chromosome? Let's talk about this logic some more.

Adrian: What are you thinking specifically is the slow down with the chunking; actually determining the chunks? Or processing some reads multiple times?

**Comment by Apb58** [comment]
Leslie:
Updated the logic to make sure the chromosome is referenced with position, such that bundling only occurs with reads in the same chromosome. 

"Standard" position *is* the position of the first read in the chunk; the idea is that the first read's position information is used to compare against every other read in the chunk. Thus, I called the first stored position "standard".

Will check on the SAM tools sorting -- I was running into some error when I was trying to do it on an example file before and chalked it up to the wrong formatting.

I've updated the logic a bit and updated the sam files which were missing the RNAME column.

**Comment by sclaridg** [comment]
I have so many ideas for my own script after reading through your outline. You've brought up ideas that I hadn't considered, e.g. position chunking. This would definitely preclude loading too many alignments into memory, though I'm wondering if your overlapping chunking method will slow your program down? It may be that I don't have a solid grasp of how your algorithm steps through the alignments. Everything else checks out in my head though... Logic is sound!

I'm a huge fan of how your functions bleed into each other. This seems like it would be really efficient.

A minor samtools thing: You can make `samtools sort` output a SAM file rather than the inputted BAM format with the `-O sam` flag.

One thing to note is that strandedness will matter (I think we were supposed to consider a non-specific library for this part of Deduper). For example, you could make a function that will determine "forward"  (e.g. `0`) or "reverse" (e.g. `16`) from the bitwise flag. Strandedness might throw a wrench in the logic you have built into your code (again, I'm having trouble wrapping my mind around how the chunking works). Reads could be on the same chromosome, have the same POS and UMI, and be on different strands, but if there is soft clipping involved, reads from the same strands could be mixed up in all the alignments for that chromosome (is this what the chunking method accounts for?). This means duplicates could be separated by non-duplicates, and I think your code would read those separated duplicates as two unique alignments. Could you save unique alignment identifiers (i.e. UMI, strand, chromosome, and starting position), which should (in theory) be entirely unique for each set of duplicates, rather than whole alignments? This kind of strategy might not jive with your chunking algorithm though...

**Pull request merged**
